### ISSUE TITLE
centre logos or text

### ISSUE THREAD

**Issue by 01micko** [01micko/mkwallpaper#1]
Add an option to centre logo icons or text but probably not both at this stage

**Comment by 01micko** [comment]
@consolatis

**Comment by 01micko** [comment]
@Consolatis


https://github.com/01micko/mkwallpaper/assets/1019119/cfc96424-cf6d-434a-abfa-436ccdc6b364

**Comment by Consolatis** [comment]
Looking good

**Comment by 01micko** [comment]
About to push a fairly big refactor (relative to the size of the code ;D ) with breaking changes, but I don't think that many folk have to worry too much.

**Comment by 01micko** [comment]
Now centres logos too and logo + text.
