### ISSUE TITLE
address the `atof` locale bug

### ISSUE THREAD

**Issue by 01micko** [01micko/mkwallpaper#6]
Need a function to parse `atof` if locale has `comma` for decimal separator ; re #2

**Comment by 01micko** [comment]
Hrmm, perhaps `atoi` has the same bug @Consolatis ?

I'm thinking thousands separator.

**Comment by Consolatis** [comment]
That is possible, at least in my case `man atoi` says:
> The behavior is the same as strtol(nptr, NULL, 10);

Which in turn says:
> According to POSIX.1, in locales other than "C" and "POSIX", these functions may  accept  other, implementation-defined numeric strings.

However I don't think this is really an issue in practicse, I don't think people use thousand separators for settings. In comparison, for floats that is a necessary part of the value.

**Comment by 01micko** [comment]
Thanks for your time to answer @Consolatis :-)

Makes sense to me.

Also, since `cairo` colors follow the `sRGB` color space requiring a non localised decimal value then I think I can safely ignore this bug. I should put  a note in the manual about the requirement for the input to have a `dot` as the decimal separator.
